[[main]]
    # Top-level menu entry
    identifier = "work"
    name = "Start Here"
    url = "/about/"
    weight = 1



[[main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    parent = "work"
    weight = 2

[[main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    parent = "work"
    weight = 3

[[main]]
    # Top-level menu entry
    identifier = "writing"
    name = "Writing"
    url = "/posts/"
    weight = 4

[[main]]
    identifier = "posts"
    name = "All Posts"
    url = "/posts/"
    parent = "writing"
    weight = 4

[[main]]
    identifier = "product"
    name = "Product Journey"
    url = "/product journey/"
    # url = "/posts/subsection/" # Remove url param from subsection/_index.md frontmatter to use full permalink
    parent = "writing"
    weight = 5

[[main]]
    identifier = "Geospatial"
    name = "Geospatial & AI"
    url = "/geospatial & AI/"
    # url = "/posts/subsection/" # Remove url param from subsection/_index.md frontmatter to use full permalink
    parent = "writing"
    weight = 5


[[main]]
    # Top-level menu entry
    identifier = "explore"
    name = "Explore"
    url = "/categories/"
    weight = 6

[[main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    parent = "explore"
    weight = 6

[[main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    parent = "explore"
    weight = 7

[[main]]
    identifier = "series"
    name = "Series"
    url = "/series/"
    parent = "explore"
    weight = 8

